--- #YAML:1.0
name:                Language-Prolog-Yaswi
version:             0.16
abstract:            Yet another interface to SWI-Prolog
license:             ~
author:              
    - Salvador Fandiño <sfandino@yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Language::Prolog::Sugar:       0.03
    Language::Prolog::Types:       0.09
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
